package com.swjt.xingzishop.Bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XzUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public XzUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("User_Id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("User_Id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("User_Id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("User_Id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("User_Id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("User_Id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("User_Id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("User_Id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("User_Id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("User_Id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("User_Id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("User_Id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("User_Id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("User_Id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("User_Name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("User_Name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("User_Name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("User_Name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("User_Name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("User_Name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("User_Name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("User_Name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("User_Name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("User_Name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("User_Name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("User_Name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("User_Name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("User_Name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("User_PassWord is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("User_PassWord is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("User_PassWord =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("User_PassWord <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("User_PassWord >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("User_PassWord >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("User_PassWord <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("User_PassWord <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("User_PassWord like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("User_PassWord not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("User_PassWord in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("User_PassWord not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("User_PassWord between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("User_PassWord not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeIsNull() {
            addCriterion("User_CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeIsNotNull() {
            addCriterion("User_CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeEqualTo(Date value) {
            addCriterion("User_CreateTime =", value, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeNotEqualTo(Date value) {
            addCriterion("User_CreateTime <>", value, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeGreaterThan(Date value) {
            addCriterion("User_CreateTime >", value, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("User_CreateTime >=", value, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeLessThan(Date value) {
            addCriterion("User_CreateTime <", value, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("User_CreateTime <=", value, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeIn(List<Date> values) {
            addCriterion("User_CreateTime in", values, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeNotIn(List<Date> values) {
            addCriterion("User_CreateTime not in", values, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeBetween(Date value1, Date value2) {
            addCriterion("User_CreateTime between", value1, value2, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("User_CreateTime not between", value1, value2, "userCreatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeIsNull() {
            addCriterion("User_UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeIsNotNull() {
            addCriterion("User_UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeEqualTo(Date value) {
            addCriterion("User_UpdateTime =", value, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeNotEqualTo(Date value) {
            addCriterion("User_UpdateTime <>", value, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeGreaterThan(Date value) {
            addCriterion("User_UpdateTime >", value, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("User_UpdateTime >=", value, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeLessThan(Date value) {
            addCriterion("User_UpdateTime <", value, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("User_UpdateTime <=", value, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeIn(List<Date> values) {
            addCriterion("User_UpdateTime in", values, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeNotIn(List<Date> values) {
            addCriterion("User_UpdateTime not in", values, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("User_UpdateTime between", value1, value2, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("User_UpdateTime not between", value1, value2, "userUpdatetime");
            return (Criteria) this;
        }

        public Criteria andUserIsbanIsNull() {
            addCriterion("User_IsBan is null");
            return (Criteria) this;
        }

        public Criteria andUserIsbanIsNotNull() {
            addCriterion("User_IsBan is not null");
            return (Criteria) this;
        }

        public Criteria andUserIsbanEqualTo(Boolean value) {
            addCriterion("User_IsBan =", value, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanNotEqualTo(Boolean value) {
            addCriterion("User_IsBan <>", value, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanGreaterThan(Boolean value) {
            addCriterion("User_IsBan >", value, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanGreaterThanOrEqualTo(Boolean value) {
            addCriterion("User_IsBan >=", value, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanLessThan(Boolean value) {
            addCriterion("User_IsBan <", value, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanLessThanOrEqualTo(Boolean value) {
            addCriterion("User_IsBan <=", value, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanIn(List<Boolean> values) {
            addCriterion("User_IsBan in", values, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanNotIn(List<Boolean> values) {
            addCriterion("User_IsBan not in", values, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanBetween(Boolean value1, Boolean value2) {
            addCriterion("User_IsBan between", value1, value2, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserIsbanNotBetween(Boolean value1, Boolean value2) {
            addCriterion("User_IsBan not between", value1, value2, "userIsban");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameIsNull() {
            addCriterion("User_LoginName is null");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameIsNotNull() {
            addCriterion("User_LoginName is not null");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameEqualTo(String value) {
            addCriterion("User_LoginName =", value, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameNotEqualTo(String value) {
            addCriterion("User_LoginName <>", value, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameGreaterThan(String value) {
            addCriterion("User_LoginName >", value, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameGreaterThanOrEqualTo(String value) {
            addCriterion("User_LoginName >=", value, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameLessThan(String value) {
            addCriterion("User_LoginName <", value, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameLessThanOrEqualTo(String value) {
            addCriterion("User_LoginName <=", value, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameLike(String value) {
            addCriterion("User_LoginName like", value, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameNotLike(String value) {
            addCriterion("User_LoginName not like", value, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameIn(List<String> values) {
            addCriterion("User_LoginName in", values, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameNotIn(List<String> values) {
            addCriterion("User_LoginName not in", values, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameBetween(String value1, String value2) {
            addCriterion("User_LoginName between", value1, value2, "userLoginname");
            return (Criteria) this;
        }

        public Criteria andUserLoginnameNotBetween(String value1, String value2) {
            addCriterion("User_LoginName not between", value1, value2, "userLoginname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XZ_User
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}