package com.swjt.xingzishop.Mapper;
import com.swjt.xingzishop.Bean.XzRole;
import com.swjt.xingzishop.Bean.XzRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface XzRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int countByExample(XzRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int deleteByExample(XzRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int insert(XzRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int insertSelective(XzRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    List<XzRole> selectByExample(XzRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    XzRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XzRole record, @Param("example") XzRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XzRole record, @Param("example") XzRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XzRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_Role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XzRole record);

    XzRole selectByUserId(String userId);
}
