package com.swjt.xingzishop.Mapper;

import com.swjt.xingzishop.Bean.XzUser;
import com.swjt.xingzishop.Bean.XzUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XzUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int countByExample(XzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int deleteByExample(XzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int insert(XzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int insertSelective(XzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    List<XzUser> selectByExample(XzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    XzUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XzUser record, @Param("example") XzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XzUser record, @Param("example") XzUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XZ_User
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XzUser record);
}